[install]
is_configured = 0
state = enabled
build = 1

[ui]
# This keeps the TA hidden from the Splunk Web navigation bar
is_visible = 0
label = TA-BigFix WebReports

[launcher]
author = BigFix Professional Services
description = Data collection add-on for BigFix WebReports servers.
version = 1.0.0

[package]
id = TA-bigfix_WebReports