[monitor://C:\Program Files (x86)\BigFix Enterprise\BES WebUI\service-wrapper.log]
disabled = 1
index = bigfix
sourcetype = bigfix:webui

[monitor://C:\Program Files (x86)\BigFix Enterprise\BES WebUI\WebUI\sites\WebUI Insights_*\insights-app\logs\imports\import-*.log]
disabled = 1
index = bigfix
sourcetype = bigfix:webui:insights