[monitor://C:\Program Files (x86)\BigFix Enterprise\BES Server\BESRelay.log]
disabled = 1
index = bigfix
sourcetype = bigfix:root:besrelay

[monitor://C:\Program Files (x86)\BigFix Enterprise\BES Server\GatherDBData\GatherDB.log]
disabled = 1
index = bigfix
sourcetype = bigfix:root:gatherdb

[monitor://C:\Program Files (x86)\BigFix Enterprise\BES Server\FillDBData\FillDB.log]
disabled = 1
index = bigfix
sourcetype = bigfix:root:filldb

[monitor://C:\Program Files (x86)\BigFix Enterprise\BES Server\server_audit*.log]
disabled = 1
index = bigfix
sourcetype = bigfix:root:audit

[monitor://C:\Program Files (x86)\BigFix Enterprise\BES Server\BESTools.log]
disabled = 1
index = bigfix
sourcetype = bigfix:root:bestools