[bigfix:root:besrelay]
category = BigFix
pulldown_type = 1
description = Parsing rules for BigFix Root Server / Relay logs

SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)(?=[A-Z][a-z]{2},\s\d{2}\s[A-Z][a-z]{2}\s\d{4}\s\d{2}:\d{2}:\d{2}\s[+-]\d{4})
TRUNCATE = 10000

TIME_PREFIX = ^
TIME_FORMAT = %a, %d %b %Y %H:%M:%S %z
MAX_TIMESTAMP_LOOKAHEAD = 35

[bigfix:root:gatherdb]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
TIME_PREFIX = ^\s*
TIME_FORMAT = %a, %d %b %Y %H:%M:%S %z
MAX_TIMESTAMP_LOOKAHEAD = 35

[bigfix:root:filldb]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
TIME_PREFIX = ^
TIME_FORMAT = %a, %d %b %Y %H:%M:%S %z
MAX_TIMESTAMP_LOOKAHEAD = 35

[bigfix:root:audit]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
TIME_PREFIX = ^\d+\|
TIME_FORMAT = %a, %d %b %Y %H:%M:%S %z
MAX_TIMESTAMP_LOOKAHEAD = 35

[bigfix:root:bestools]
DESCRIPTION = BigFix BESTools Log Parsing
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)(?=(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun),\s\d{2}\s(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s\d{4}\s\d{2}:\d{2}:\d{2}\s[+-]\d{4}\s--\s)

TIME_PREFIX = ^
TIME_FORMAT = %a, %d %b %Y %H:%M:%S %z
MAX_TIMESTAMP_LOOKAHEAD = 40

TRUNCATE = 999999

ANNOTATE_PUNCT = false
KV_MODE = none